sonar.projectKey=GitUserMaxim_php-project-57
sonar.organization=gitusermaxim

sonar.php.coverage.reportPaths=build/logs/clover.xml

sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**
sonar.exclusions=vendor/**,storage/**,bootstrap/**

sonar.sourceEncoding=UTF-8
